# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='product.proto',
  package='catalog',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rproduct.proto\x12\x07\x63\x61talog\"#\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1f\n\x11GetProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"4\n\x0fGetProductReply\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.catalog.Product\"\x06\n\x04Ping\"\x06\n\x04Pong2\x83\x01\n\x0eProductService\x12\x42\n\nGetProduct\x12\x1a.catalog.GetProductRequest\x1a\x18.catalog.GetProductReply\x12-\n\x0bHealthCheck\x12\r.catalog.Ping\x1a\r.catalog.Pong\"\x00\x62\x06proto3')
)




_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='catalog.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='catalog.Product.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='catalog.Product.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=61,
)


_GETPRODUCTREQUEST = _descriptor.Descriptor(
  name='GetProductRequest',
  full_name='catalog.GetProductRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='catalog.GetProductRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=94,
)


_GETPRODUCTREPLY = _descriptor.Descriptor(
  name='GetProductReply',
  full_name='catalog.GetProductReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product', full_name='catalog.GetProductReply.product', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=148,
)


_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='catalog.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=156,
)


_PONG = _descriptor.Descriptor(
  name='Pong',
  full_name='catalog.Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=164,
)

_GETPRODUCTREPLY.fields_by_name['product'].message_type = _PRODUCT
DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
DESCRIPTOR.message_types_by_name['GetProductRequest'] = _GETPRODUCTREQUEST
DESCRIPTOR.message_types_by_name['GetProductReply'] = _GETPRODUCTREPLY
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['Pong'] = _PONG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCT,
  __module__ = 'product_pb2'
  # @@protoc_insertion_point(class_scope:catalog.Product)
  ))
_sym_db.RegisterMessage(Product)

GetProductRequest = _reflection.GeneratedProtocolMessageType('GetProductRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPRODUCTREQUEST,
  __module__ = 'product_pb2'
  # @@protoc_insertion_point(class_scope:catalog.GetProductRequest)
  ))
_sym_db.RegisterMessage(GetProductRequest)

GetProductReply = _reflection.GeneratedProtocolMessageType('GetProductReply', (_message.Message,), dict(
  DESCRIPTOR = _GETPRODUCTREPLY,
  __module__ = 'product_pb2'
  # @@protoc_insertion_point(class_scope:catalog.GetProductReply)
  ))
_sym_db.RegisterMessage(GetProductReply)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), dict(
  DESCRIPTOR = _PING,
  __module__ = 'product_pb2'
  # @@protoc_insertion_point(class_scope:catalog.Ping)
  ))
_sym_db.RegisterMessage(Ping)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), dict(
  DESCRIPTOR = _PONG,
  __module__ = 'product_pb2'
  # @@protoc_insertion_point(class_scope:catalog.Pong)
  ))
_sym_db.RegisterMessage(Pong)



_PRODUCTSERVICE = _descriptor.ServiceDescriptor(
  name='ProductService',
  full_name='catalog.ProductService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=167,
  serialized_end=298,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProduct',
    full_name='catalog.ProductService.GetProduct',
    index=0,
    containing_service=None,
    input_type=_GETPRODUCTREQUEST,
    output_type=_GETPRODUCTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HealthCheck',
    full_name='catalog.ProductService.HealthCheck',
    index=1,
    containing_service=None,
    input_type=_PING,
    output_type=_PONG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTSERVICE)

DESCRIPTOR.services_by_name['ProductService'] = _PRODUCTSERVICE

# @@protoc_insertion_point(module_scope)
