# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import wishlist_pb2 as wishlist__pb2


class WishlistServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPing = channel.unary_unary(
        '/GrpcWishlist.WishlistService/GetPing',
        request_serializer=wishlist__pb2.Ping.SerializeToString,
        response_deserializer=wishlist__pb2.Pong.FromString,
        )
    self.GetWishlist = channel.unary_unary(
        '/GrpcWishlist.WishlistService/GetWishlist',
        request_serializer=wishlist__pb2.WishlistRequest.SerializeToString,
        response_deserializer=wishlist__pb2.WishlistResponse.FromString,
        )
    self.AddToWishList = channel.unary_unary(
        '/GrpcWishlist.WishlistService/AddToWishList',
        request_serializer=wishlist__pb2.WishlistAddRequest.SerializeToString,
        response_deserializer=wishlist__pb2.Response.FromString,
        )


class WishlistServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPing(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetWishlist(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddToWishList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WishlistServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPing': grpc.unary_unary_rpc_method_handler(
          servicer.GetPing,
          request_deserializer=wishlist__pb2.Ping.FromString,
          response_serializer=wishlist__pb2.Pong.SerializeToString,
      ),
      'GetWishlist': grpc.unary_unary_rpc_method_handler(
          servicer.GetWishlist,
          request_deserializer=wishlist__pb2.WishlistRequest.FromString,
          response_serializer=wishlist__pb2.WishlistResponse.SerializeToString,
      ),
      'AddToWishList': grpc.unary_unary_rpc_method_handler(
          servicer.AddToWishList,
          request_deserializer=wishlist__pb2.WishlistAddRequest.FromString,
          response_serializer=wishlist__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GrpcWishlist.WishlistService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class ItemsServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetItems = channel.unary_unary(
        '/GrpcWishlist.ItemsService/GetItems',
        request_serializer=wishlist__pb2.ItemsRequest.SerializeToString,
        response_deserializer=wishlist__pb2.ItemsResponse.FromString,
        )


class ItemsServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetItems(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ItemsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetItems': grpc.unary_unary_rpc_method_handler(
          servicer.GetItems,
          request_deserializer=wishlist__pb2.ItemsRequest.FromString,
          response_serializer=wishlist__pb2.ItemsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GrpcWishlist.ItemsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
