version: '3'
services:
  client:
    build: ./client
    environment:
    - WISHLIST_ENDPOINT=wishlist
    - PRODUCT_ENDPOINT=product-catalog
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
  postgres:
    image: postgres
    ports:
      - 5432:5432
  wishlist:
    build: ./wishlist-ms/Wishlist/WishlistServer
    environment:
            - REDIS_ENDPOINT=redis
            - ITEMS_MS_ENDPOINT=product-catalog
    ports:
      - "8080:50051"   
  users:
    build: ./users-ms/
    environment:
      - MS_HOST=users
      - PG_USER="users"
      - PG_HOST=postgres
      - PG_DATABASE="users"
      - PG_PASSWORD="users"
  mongo:
    image: mongo
    ports:
      - "27071:27071"
  product-catalog:
    image: product-catalog-ms:0.1.0-SNAPSHOT
    ports:
      - "50000:50000"
    environment:
      - MONGO_IP=mongo