version: '3'

services:
  db:
    image: postgres
    container_name: "users_db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users
      POSTGRES_DB: users